networks:
  social_network:
    driver: bridge


services:
  mysql:
    image: mysql:8.0
    container_name: social_mysql
    volumes:
      - ./data/db_data_mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'  # Buộc tất cả kết nối sử dụng utf8mb4
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: social_media
      MYSQL_PASSWORD: root1234
    ports:
      - "3316:3306"
    networks:
      - social_network